### PR TITLE
Exhibit fixes, css changes, ed25519 support

### PR DESCRIPTION
**Pull request by swandog30**
Address #242 #243 #256 and css layout changes for exhibit navigation

### CODE REVIEW

**Comment by swandog30** [comment]
@DanOlson, can you take a look please, specifically if its ok to push up the react changes.  Thanks!

**Review by DanOlson — CHANGES_REQUESTED** [review]
@swandog30 with the exception of the changes to `bin/install_nginx_conf` and [these two lines in mdl.scss](https://github.com/Minitex/mdl_search/pull/260/files#diff-64ef8ef2a2effb9fa2dfb6901fbb44f16771224b31e75a0dd86bffd0811e752dL336-R338) this stuff is all merged already. It looks like there are several duplicate commits here which should get removed. I think the only ones we want to keep are 9b72029 and 2b291ed

**Comment by swandog30** [comment]
@DanOlson I think I have this set properly now, please take a look.  I made a copy of the develop branch in case I messed it all up.

**Review by DanOlson — APPROVED** [review]
Looks good, @swandog30!

**Pull request merged**
